# Generated by Django 2.2.1 on 2019-06-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productgroups_products_sfcombinations_sfitem_sfvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductGroups',
            new_name='ProductGroup',
        ),
        migrations.RenameModel(
            old_name='SFCombinations',
            new_name='SFCombination',
        ),
    ]
